from django.urls import path
from .views import (home, LibroListView, LibroDetailView, AutorListView, AutorDetailView, 
                    GeneroListView, GeneroDetailView, SearchResultsListViewLibro, SearchResultsListViewAutor,
                    contacto, LibroCreate, LibroUpdate, LibroDelete, AutorCreate, AutorUpdate, AutorDelete,
                    ReseñaCreate, ReseñaUpdate, ReseñaDelete, UsuarioCreate, ListaLecturaListView,
                    ListaLecturaDetailView, ListaLecturaCreate, ListaLecturaUpdate, ListaLecturaDelete)

urlpatterns = [
    path('', home, name='home'),
    path('libros/', LibroListView.as_view(), name='lista-libros'),
    path('libros/<int:pk>', LibroDetailView.as_view(), name='detalle-libro'),
    path('autores/', AutorListView.as_view(), name='lista-autores'),
    path('autores/<int:pk>', AutorDetailView.as_view(), name='detalle-autor'), 
    path('generos/', GeneroListView.as_view(), name='lista-generos'),
    path('generos/<int:pk>', GeneroDetailView.as_view(), name='detalle-genero'),
    path('listas/', ListaLecturaListView.as_view(), name='lista-lectura'),
    path('listas/<int:pk>', ListaLecturaDetailView.as_view(), name='detalle-lista'),
    path('busqueda/', SearchResultsListViewLibro.as_view(), name='buscar'),
    path('buscar/', SearchResultsListViewAutor.as_view(), name='busqueda'),
    path('contacto/', contacto, name='contacto'),
    path('libro/crear/', LibroCreate.as_view(), name='crear-libro'),
    path('libro/<int:pk>/actualizar/', LibroUpdate.as_view(), name='actualizar-libro'),
    path('libro/<int:pk>/eliminar/', LibroDelete.as_view(), name='eliminar-libro'),
    path('autor/crear/', AutorCreate.as_view(), name='crear-autor'),
    path('autor/<int:pk>/actualizar/', AutorUpdate.as_view(), name='actualizar-autor'),
    path('autor/<int:pk>/eliminar/', AutorDelete.as_view(), name='eliminar-autor'),
    path('reseña/crear/', ReseñaCreate.as_view(), name='crear-reseña'),
    path('reseña/<int:pk>/actualizar/', ReseñaUpdate.as_view(), name='actualizar-reseña'),
    path('reseña/<int:pk>/eliminar/', ReseñaDelete.as_view(), name='eliminar-reseña'),
    path('lista/crear/', ListaLecturaCreate.as_view(), name='crear-lista'),
    path('lista/<int:pk>/actualizar/', ListaLecturaUpdate.as_view(), name='actualizar-lista'),
    path('lista/<int:pk>/eliminar/', ListaLecturaDelete.as_view(), name='eliminar-lista'),
    path('registrarse/', UsuarioCreate.as_view(), name='registrarse'),
]