# Generated by Django 5.0.4 on 2024-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(help_text='Ingrese una breve descripción del libro'),
        ),
    ]
