# Generated by Django 5.0.4 on 2024-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_precio_alter_libro_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='calificacion',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
